SELECT TOP (1000) [Ssn]
      ,[Fname]
      ,[Minit]
      ,[Lname]
      ,[Address]
      ,[Sex]
      ,[Bdate]
      ,[Salary]
      ,[DepartmentNumber]
      ,[SupervisorSSN]
  FROM [CompanyDB].[dbo].[Employee]
